spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commentdb
    username: root
    password: Ranjeet@12
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8082
